"""Generate assets/css/foundation-subset.css from the vendored Foundation build.

Foundation for Sites 6.9.0 ships ~131 KB but this site uses only its global base
(normalize + box-sizing, body/heading/img/link defaults) and five classes:
grid-container, grid-x, cell, button, show-for-sr. This keeps every rule whose
selectors reference no other Foundation class -- so the whole element-level base is
preserved untouched -- plus the rules for those five classes, and drops the rest
(components, the responsive grid width/offset system, button variants, etc.).

Re-run after replacing assets/vendor/foundation.min.css. Standard library only.

    python3 scripts/subset-foundation.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'assets/vendor/foundation.min.css'
OUT = ROOT / 'assets/css/foundation-subset.css'
USED = {'grid-container', 'grid-x', 'cell', 'button', 'show-for-sr'}


def classes(selector):
    return set(re.findall(r'\.([A-Za-z0-9_-]+)', selector))


def keep_selector_list(selectors):
    """Keep only the comma-separated selectors whose classes are all in USED."""
    kept = [s for s in selectors.split(',') if classes(s) <= USED]
    return ','.join(kept)


def transform(css):
    """Walk top-level rules and @media blocks, keeping qualifying declarations."""
    out = []
    i, n = 0, len(css)
    while i < n:
        if css[i] in ' \n\t':
            i += 1
            continue
        if css.startswith('@charset', i):
            i = css.index(';', i) + 1
            continue
        media = re.match(r'@media[^{]*\{', css[i:])
        if media:
            depth, j = 0, i
            while j < n:
                if css[j] == '{':
                    depth += 1
                elif css[j] == '}':
                    depth -= 1
                    if depth == 0:
                        break
                j += 1
            header = css[i:i + media.end() - 1]
            inner = transform(css[i + media.end():j])
            if inner.strip():
                out.append(header + '{' + inner + '}')
            i = j + 1
            continue
        if css.startswith('@', i):
            # Drop other at-rules (keyframes, font-face); none are used by the kept rules.
            if css.startswith('@font-face', i) or re.match(r'@[\w-]+[^{;]*\{', css[i:]):
                depth, j = 0, css.index('{', i)
                while j < n:
                    if css[j] == '{':
                        depth += 1
                    elif css[j] == '}':
                        depth -= 1
                        if depth == 0:
                            break
                    j += 1
                i = j + 1
            else:
                i = css.index(';', i) + 1
            continue
        brace = css.find('{', i)
        if brace == -1:
            break
        end = css.index('}', brace)
        selectors, body = css[i:brace], css[brace + 1:end]
        kept = keep_selector_list(selectors)
        if kept:
            out.append(kept + '{' + body + '}')
        i = end + 1
    return ''.join(out)


def main():
    css = re.sub(r'/\*.*?\*/', '', SOURCE.read_text(), flags=re.S)
    subset = ('/* Subset of Foundation for Sites 6.9.0 (MIT) -- global base plus the\n'
              '   grid-container, grid-x, cell, button and show-for-sr classes this site\n'
              '   uses. Generated by scripts/subset-foundation.py; do not edit by hand.\n'
              '   Full library and license: assets/vendor/. */\n') + transform(css) + '\n'
    OUT.write_text(subset)
    print(f'Wrote {OUT.relative_to(ROOT)} ({len(subset):,} bytes from {len(css):,}).')


if __name__ == '__main__':
    main()
